In [1]:
# compare simulated and observed flow
import os
from datetime import datetime, timedelta
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import matplotlib as mpl
from matplotlib.dates import (YEARLY, DateFormatter,
                              rrulewrapper, RRuleLocator, drange)
from PIL import Image
import pandas as pd

def datetime_range(start, end, delta):
    current = start
    while current < end:
        yield current
        current += delta
        
#================================ Plot =======================================
def plot_hyd(t_plot, obs, sim, title_str, plot_file):
    
    row_num=1
    col_num=1        
    fig, ax = plt.subplots(row_num,col_num)
    fig.set_figwidth(6.5*col_num) #190mm
    fig.set_figheight(6.5*0.4*row_num) #5.61 heigh/width=3/4

    dpi_value=100
    formatter = DateFormatter('%m/%d/%y')
    # formatter = DateFormatter('%b-%y')
    
    ax.plot_date(t_plot, obs, color='darkorange', linestyle='-', linewidth=1.5, markersize=0.0, alpha=0.8, label='Observation')   
    ax.plot_date(t_plot, sim, color='black', linestyle='--', linewidth=1.5, markersize=0.0, alpha=0.8, label='Simulation') 

    #axis, label, title, legend
    ax.set_title(title_str, fontsize='small', fontweight='bold')
    ax.set_xlabel('Date', fontsize='small')
    ax.set_ylabel('Flow $(cms)$', fontsize='small')
    
    ax.set_xlim(t_plot[0],t_plot[-1])
    ax.xaxis.set_major_formatter(formatter)
    ax.xaxis.set_tick_params(labelsize='small')#rotation=30,
    ax.legend(loc='upper left', fontsize='small', framealpha=0.5) #loc='upper right', 

    plt.rc('xtick',labelsize='small')
    plt.rc('ytick',labelsize='small') 
    plt.grid(True,linewidth=0.5,alpha=0.5)
    
    fig.tight_layout()
    fig.savefig(plot_file, dpi=dpi_value)
    plt.close(fig)      
    del fig
    
    return os.path.join(plot_file)

#===============================================================================

# Main script
root_dir = '/glade/u/home/hongli/work/russian/model'
model = 'mendocino_270m_GW'
sim_prj_file = os.path.join(root_dir, model,'run/mendocino_270m.prj')
sim_lc_file = os.path.join(root_dir, model,'input/mendocino_270m.ihl_Labels')
sim_file = os.path.join(root_dir, model,'output/mendocino_270m.ohl')
obs_dir = os.path.join(root_dir,'analysis/Mendocino_Observed_StreamFlow_Data/2018_2019_measured_hydrographs')

script_dir = 'analysis/'
output_folder='step4_plot_hydro_2018_WRF_GW_rate_15min'
output_file = 'OUT_HYD_LOCATION_GW.png'
if not os.path.exists(os.path.join(root_dir, script_dir, output_folder)):
    os.mkdir(os.path.join(root_dir, script_dir, output_folder))

# =========================== read simuated flow ===========================
print('read simuated flow')
# lc_names = np.loadtxt(os.path.join(root_dir, sim_lc_file), skiprows=1, usecols=[2], dtype='str')
lc_names = ['Hopland (USGS)', 'Talmage (USGS) (11462080)', 'Ukiah (USGS)', 'Calpella (USGS)', 
            'DRW - Perry Creek - Deerwood', 'CLD - Cold Creek','MEW - Delbar Ranch', 
            'WHT - White Creek', 'BYS - Boyes Creek', 'MLL - Mill Creek', 
            'Coyote Outflow', 'Potter West', 'Potter Powerhouse', 'Potter East']    
sim_data = np.loadtxt(os.path.join(root_dir, sim_file), usecols=range(1,len(lc_names)+1))

# read output times in string
with open(sim_prj_file, 'r') as f:
    for line in f:
        line = line.strip()
        if line and line.startswith('START_DATE'):
            start_date_splits = line.split()[1:]
        elif line and line.startswith('START_TIME'):
            start_time_splits = line.split()[1:]
        elif line and line.startswith('END_TIME'): 
            end_dt_splits = line.split()[1:]
start_date_splits = [int(x) for x in start_date_splits]
start_time_splits = [int(x) for x in start_time_splits]
end_dt_splits = [int(x) for x in end_dt_splits]            

# convert string to datetime (known interval = 15min)
start_datetime = datetime(start_date_splits[0], start_date_splits[1], start_date_splits[2], start_time_splits[0], start_time_splits[1])
dts_datetime = [start_datetime+timedelta(minutes=15*i) for i in range(np.shape(sim_data)[0])]
end_datetime = dts_datetime[-1]
dts_str = [dt.strftime('%Y-%m-%d %H:%M:%S') for dt in dts_datetime]
# print(start_datetime,end_datetime)

# create dataframe (time, data)
df1 = pd.DataFrame(sim_data,columns=lc_names)
df1['datetime'] = dts_datetime
df1 = df1.set_index('datetime')

# =========================== process flow results ===========================
print('process flow results')
t_plot = pd.to_datetime(df1.index)

# convert flow unit from cms to m^3 in million
df_sim = df1

# =========================== plot =========================== 
print('plot')
lc_names_index = range(len(lc_names))
fig_file_summary = []
alpha = 'a'
for i in range(len(lc_names_index)):
# for i in range(10,12):
    lc_name = lc_names[lc_names_index[i]]
    obs_file = lc_name + '.xlsx'
    
    # read obs data
    if os.path.exists(os.path.join(root_dir, obs_dir, obs_file)):
        df2 = pd.read_excel(os.path.join(root_dir, obs_dir, obs_file), converters= {'date and time': pd.to_datetime}) #index_col=[0], 
        mask = (df2['date and time'] >= dts_str[0]) & (df2['date and time'] <= dts_str[-1]) #Use a boolean mask
        df_obs = df2.loc[mask, ['date and time','flow (cms)']]

        # fill missing obs 
        dts_obs_str = [dt.strftime('%Y-%m-%d %H:%M:%S') for dt in df_obs['date and time']]
        obs_fill = []
        for j in range(len(df1)):
            dt = dts_str[j]
            if dt in dts_obs_str:
                obs_index = dts_obs_str.index(dt)
                obs_value = df_obs.iloc[obs_index]['flow (cms)']
                if obs_value != -999.0:
                    obs_fill.append(obs_value)
            else:
                obs_fill.append(np.nan)
        del df2, df_obs, dts_obs_str
    else:
        obs_fill = np.empty((len(df1),))
        obs_fill[:] = np.nan
    
    # aggrate observation to daily volume
    df_obs = pd.Series(obs_fill, index=df1.index)
        
    # plot    
    title_str = '('+chr(ord(alpha) + i) +') ' + lc_name
    print(title_str)
    
    plot_file = os.path.join(root_dir, script_dir, output_folder, lc_name+'.png')
    fig_file = plot_hyd(t_plot=t_plot, obs = df_obs.values, sim = df_sim.loc[:,lc_name].values, 
                        title_str = title_str, plot_file = plot_file)
    
    fig_file_summary.append(fig_file)  
    del obs_fill, df_obs
    
# =========================== merge and save =========================== 
# save as one figure for all
print('save')
os.chdir(os.path.join(root_dir, script_dir, output_folder))
widths = []
heights = []
for fig_file in fig_file_summary:
    im = Image.open(fig_file)
    widths.append(im.width)
    heights.append(im.height)

max_width = int(max(widths)*2)
total_height = int(sum(heights)/2)
new_im = Image.new('RGB', (max_width, total_height))

for col in range(2):
    for row in range(int(len(fig_file_summary)/2)):
        
        fig_file = fig_file_summary[row*2+col]
        im = Image.open(fig_file)   
        
        x_offset_width = im.size[0]
        x_offset_height = im.size[1]

        new_im.paste(im, (x_offset_width*col,x_offset_height*row))
new_im.save(os.path.join(root_dir, script_dir, output_folder, output_file))    

print('Done')

read simuated flow
process flow results
plot
(a) Hopland (USGS)

/glade/u/home/hongli/tools/miniconda/ENTER/lib/python3.7/site-packages/pandas/plotting/_matplotlib/converter.py:103: FutureWarning: Using an implicitly registered datetime converter for a matplotlib plotting method. The converter was registered by pandas on import. Future versions of pandas will require you to explicitly register matplotlib converters.

To register the converters:
	>>> from pandas.plotting import register_matplotlib_converters
	>>> register_matplotlib_converters()
  warnings.warn(msg, FutureWarning)

NameError: name 'df_obs_volume' is not defined

In [6]:
obs_index,np.shape(df_obs)

(9304, (9304, 2))

In [18]:
df_obs.iloc[0:2],df1.iloc[0:2]

(        date and time  flow (cms)
 0 2018-01-01 00:00:00    0.192838
 1 2018-01-01 00:15:00    0.192838,
                      Hopland (USGS)  Talmage (USGS) (11462080)  Ukiah (USGS)  \
 datetime
 2018-01-01 00:00:00        0.000000                   0.000000       0.00000
 2018-01-01 00:15:00        1.185944                   1.393739       0.28953

                      Calpella (USGS)  DRW - Perry Creek - Deerwood  \
 datetime
 2018-01-01 00:00:00           0.0000                      0.000000
 2018-01-01 00:15:00           0.9532                      0.067937

                      CLD - Cold Creek  MEW - Delbar Ranch  WHT - White Creek  \
 datetime
 2018-01-01 00:00:00          0.000000            0.000000           0.000000
 2018-01-01 00:15:00          0.471932            0.080103           0.104822

                      BYS - Boyes Creek  MLL - Mill Creek  Coyote Outflow  \
 datetime
 2018-01-01 00:00:00           0.000000          0.000000        0.000000
 2018-01-01 00:15:00           0.070419          0.229566        1.780483

                      Potter West  Potter Powerhouse  Potter East
 datetime
 2018-01-01 00:00:00     0.000000           0.000000     0.000000
 2018-01-01 00:15:00     0.424301           1.299824     0.357258  )

In [19]:
len(df_obs),len(df1)

(9304, 9321)

In [30]:
df[start_t_str:end_t_str]

,Hopland (USGS),Talmage (USGS) (11462080),Ukiah (USGS),Calpella (USGS),DRW - Perry Creek - Deerwood,CLD - Cold Creek,MEW - Delbar Ranch,WHT - White Creek,BYS - Boyes Creek,MLL - Mill Creek,Coyote Outflow,Potter West,Potter Powerhouse,Potter East
datetime,,,,,,,,,,,,,,
2018-04-07 00:00:00,303.589967,276.041785,162.829266,151.643621,3.675536,22.193257,1.516424,2.525557,4.132017,19.417303,1.065086,19.317246,1.302028,6.605102
2018-04-07 00:15:00,303.659938,274.550808,162.311803,149.685950,3.751570,22.765233,1.650693,2.669170,4.469499,20.348599,1.074624,20.019169,1.308491,6.805517
2018-04-07 00:30:00,303.416699,273.238090,161.783944,147.897844,3.750432,23.026586,1.640107,2.795056,4.706834,21.091451,1.083285,20.597449,1.315564,7.043115
2018-04-07 00:45:00,302.978471,272.128640,161.351818,146.123411,3.735066,23.492381,1.771659,2.893035,4.931495,21.675708,1.090909,21.088113,1.324879,7.329051
2018-04-07 01:00:00,302.417001,271.237582,161.088405,144.613952,3.771971,23.632941,1.728998,2.973467,5.128873,22.186760,1.097529,21.540207,1.336238,7.664477
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-04-08 01:00:00,46.059241,28.401973,10.326758,10.935520,0.094429,1.502201,0.068258,0.064663,0.048104,1.385980,0.934714,0.304820,0.288620,0.054311
2018-04-08 01:15:00,44.437419,27.477619,10.006615,10.612386,0.083022,1.457767,0.055603,0.063267,0.050408,1.353450,0.934419,0.294033,0.299021,0.052702
2018-04-08 01:30:00,42.883499,26.608009,9.704766,10.312173,0.133217,1.425234,0.047193,0.061421,0.044816,1.323207,0.934124,0.284928,0.309424,0.051271
2018-04-08 01:45:00,41.398293,25.788793,9.424784,10.021477,0.094478,1.363491,0.045643,0.059459,0.045106,1.293108,0.933829,0.276346,0.319830,0.049977
2018-04-08 02:00:00,39.981984,25.016703,9.168027,9.729077,0.080588,1.307946,0.057998,0.059368,0.041192,1.263286,0.933534,0.266685,0.330350,0.048794